name: Build
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - run: |
      
        gcc mi-thermal-crypt.c cmdline.c -o mi-thermal-crypt -lssl -lcrypto
        mkdir nonexistent_path
        mv my_thermal nonexistent_path
        mv mi-thermal-crypt nonexistent_path
        mv decrypt_thermal.sh nonexistent_path
        cd nonexistent_path
        chmod 777 mi-thermal-crypt
        chmod 777 decrypt_thermal.sh
        ./decrypt_thermal.sh
        sleep 3

    - uses: actions/upload-artifact@v4

      with:

        name: idk

        path: nonexistent_path
